# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eskin_cpp <- function(r, s, num_cat, dat_vec, w, sum_w) {
    .Call(`_nomclust_eskin_cpp`, r, s, num_cat, dat_vec, w, sum_w)
}

good1_cpp <- function(r, s, dat_vec, freq_rel, freq_rel2, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_good1_cpp`, r, s, dat_vec, freq_rel, freq_rel2, freq_rel_r, w, sum_w)
}

good2_cpp <- function(r, s, dat_vec, freq_rel, freq_rel2, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_good2_cpp`, r, s, dat_vec, freq_rel, freq_rel2, freq_rel_r, w, sum_w)
}

good3_cpp <- function(r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_good3_cpp`, r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w)
}

good4_cpp <- function(r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_good4_cpp`, r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w)
}

iof_cpp <- function(r, s, dat_vec, freq_abs, freq_abs_r, w, sum_w) {
    .Call(`_nomclust_iof_cpp`, r, s, dat_vec, freq_abs, freq_abs_r, w, sum_w)
}

lin1_cpp <- function(r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_lin1_cpp`, r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w)
}

lin_cpp <- function(r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w) {
    .Call(`_nomclust_lin_cpp`, r, s, dat_vec, freq_rel, freq_rel_r, w, sum_w)
}

of_cpp <- function(r, s, dat_vec, freq_abs, freq_abs_r, n, w, sum_w) {
    .Call(`_nomclust_of_cpp`, r, s, dat_vec, freq_abs, freq_abs_r, n, w, sum_w)
}

sm_cpp <- function(r, s, dat_vec, w, sum_w) {
    .Call(`_nomclust_sm_cpp`, r, s, dat_vec, w, sum_w)
}

ve_cpp <- function(r, s, dat_vec, norm_entropy, w, sum_w) {
    .Call(`_nomclust_ve_cpp`, r, s, dat_vec, norm_entropy, w, sum_w)
}

vm_cpp <- function(r, s, dat_vec, norm_gini, w, sum_w) {
    .Call(`_nomclust_vm_cpp`, r, s, dat_vec, norm_gini, w, sum_w)
}

